<script lang="ts">
	import { onMount } from 'svelte';
	import { api, type RecordValue } from '$lib/api';
	import AdvancedConfigEditor from '$lib/AdvancedConfigEditor.svelte';

	export let artifacts: RecordValue[] = [];
	export let onnotice: (message: string) => void;
	export let onfailure: (message: string) => void;
	export let ontrain: (draftId: string) => void;

	const records = (value: unknown): RecordValue[] => Array.isArray(value) ? value as RecordValue[] : [];
	const record = (value: unknown): RecordValue => value && typeof value === 'object' ? value as RecordValue : {};
	const value = (source: RecordValue, path: string, fallback: unknown = ''): unknown => path.split('.').reduce<unknown>((current, key) => current && typeof current === 'object' ? (current as RecordValue)[key] : undefined, source) ?? fallback;
	const setPath = (target: RecordValue, path: string, next: unknown) => { const keys = path.split('.'); let current = target; for (const key of keys.slice(0, -1)) current = (current[key] as RecordValue | undefined) ?? (current[key] = {}); current[keys.at(-1)!] = next; };
	const copy = <T,>(item: T): T => JSON.parse(JSON.stringify(item));

	let drafts: RecordValue[] = [];
	let selected: RecordValue | null = null;
	let name = 'Untitled V2 classifier';
	let config: RecordValue = preset('resnet18');
	let loading = true;
	let saving = false;
	let report: RecordValue | null = null;
	let sourceArtifactId = '';
	let dragIndex: number | null = null;
	function modelDefaults(family: string): RecordValue {
		if (family.startsWith('resnet')) { const blocks: Record<string, number[]> = { resnet18: [2, 2, 2, 2], resnet34: [3, 4, 6, 3], resnet50: [3, 4, 6, 3], resnet101: [3, 4, 23, 3], resnet152: [3, 8, 36, 3] }; return { variant: family, base_filters: 64, stem_kernel_size: 3, stem_stride: 1, stem_pool: false, block_counts: blocks[family] ?? [2, 2, 2, 2], embedding_dim: 256, normalize_embeddings: false, dropout: 0.2 }; }
		if (family.startsWith('densenet')) { const blocks: Record<string, number[]> = { densenet121: [6, 12, 24, 16], densenet169: [6, 12, 32, 32], densenet201: [6, 12, 48, 32] }; return { variant: family, growth_rate: 32, initial_filters: 64, bottleneck_multiplier: 4, compression: 0.5, stem_kernel_size: 7, stem_stride: 2, stem_pool: true, block_config: blocks[family] ?? [6, 12, 24, 16], embedding_dim: 256, normalize_embeddings: true, dropout: 0.2 }; }
		if (family.startsWith('efficientnet_v2')) return { variant: family, stem_kernel_size: 3, stem_stride: 2, stem_filters: 32, top_filters: 1280, width_coefficient: 1, depth_coefficient: 1, se_ratio: 0.25, embedding_dim: 256, normalize_embeddings: true, dropout: 0.2 };
		if (family.startsWith('convnext')) return { variant: family, stage_depths: family === 'convnext_small' ? [3, 3, 27, 3] : [3, 3, 9, 3], stage_widths: [96, 192, 384, 768], stem_kernel_size: 4, stem_stride: 4, drop_path: 0, embedding_dim: 256 };
		if (family.startsWith('mobilenet')) return { variant: family, stage_widths: family === 'mobilenet_v3_large' ? [16, 24, 40, 80, 112, 160] : [16, 24, 40, 48, 96], stage_repeats: family === 'mobilenet_v3_large' ? [1, 2, 3, 3, 2, 3] : [1, 2, 2, 2, 3], expansion: 4, stem_kernel_size: 3, stem_stride: 2, stem_filters: 16, embedding_dim: 256 };
		return { base_filters: 32, embedding_dim: 256, normalize_embeddings: true, dropout: 0.2 };
	}

	function preset(family: string): RecordValue {
		return {
			architecture: { version: 2 },
			run: { task: 'classification', model: family },
			data: { input_shape: [128, 128, 1] },
			input: { channels: ['intensity'], geometry: { type: 'preserve_aspect_pad' } },
			encoder: { family, variant: family },
			stem: { kernel_size: 3, stride: 1, pool: 'none' },
			normalization: { type: 'batch' },
			pooling: { type: 'avg' },
			image_embedding: { projection: { type: 'identity' } },
			metadata: { fields: [], encoder: { type: 'direct' }, augmentation: { gaussian_variance: 0 } },
			fusion: { type: 'concat' }, classifier: { type: 'linear' },
			posthoc: { enabled: false, representation: 'fused_embedding', estimator: 'logistic_regression' },
			model: modelDefaults(family)
		};
	}
	function fields(): RecordValue[] { const current = value(config, 'metadata.fields', []); return records(current); }
	function mutate(path: string, raw: unknown) { const next = copy(config); setPath(next, path, raw); config = next; report = null; }
	function setFamily(family: string) { const next = preset(family); next.metadata = value(config, 'metadata', next.metadata); next.classifier = value(config, 'classifier', next.classifier); next.posthoc = value(config, 'posthoc', next.posthoc); config = next; report = null; }
	function addMetadata() { const next = copy(config); const current = fields(); setPath(next, 'metadata.fields', [...current, { name: `field_${current.length + 1}`, source: 'metadata.', transform: 'identity' }]); config = next; }
	function removeMetadata(index: number) { const next = copy(config); setPath(next, 'metadata.fields', fields().filter((_, item) => item !== index)); config = next; }
	function reorderMetadata(index: number) { if (dragIndex === null || dragIndex === index) return; const items = [...fields()]; const [moved] = items.splice(dragIndex, 1); items.splice(index, 0, moved); const next = copy(config); setPath(next, 'metadata.fields', items); config = next; dragIndex = null; }
	function updateMetadata(index: number, key: string, raw: string) { const next = copy(config); const items = fields().map((item, itemIndex) => itemIndex === index ? { ...item, [key]: raw } : item); setPath(next, 'metadata.fields', items); config = next; }
	function estimateParameters() {
		// Encoder values exclude the task head. They are intentionally estimates:
		// custom stages and normalization choices are finalized by backend preview.
		const encoders: Record<string, { base: number; width: number }> = {
			resnet18: { base: 11_180_000, width: 512 }, densenet121: { base: 6_955_000, width: 1024 },
			efficientnet_v2_b0: { base: 5_300_000, width: 1280 }, convnext_tiny: { base: 27_800_000, width: 768 },
			mobilenet_v3_small: { base: 2_200_000, width: 576 }
		};
		const encoder = encoders[String(value(config, 'encoder.family', 'resnet18'))] ?? encoders.resnet18;
		const classes = Math.max(2, Number(value(config, 'data.num_classes', 2)) || 2);
		const metadataWidth = fields().length;
		const projectionType = String(value(config, 'image_embedding.projection.type', 'identity'));
		const embeddingWidth = projectionType === 'identity' ? encoder.width : Math.max(1, Number(value(config, 'image_embedding.projection.output_dim', 256)) || 256);
		let total = encoder.base + (projectionType === 'identity' ? 0 : encoder.width * embeddingWidth + embeddingWidth);
		const fusedWidth = embeddingWidth + metadataWidth;
		if (String(value(config, 'classifier.type', 'linear')) === 'prototype') {
			total += fusedWidth * classes * Math.max(1, Number(value(config, 'classifier.prototypes_per_class', 1)) || 1);
		} else total += fusedWidth * classes + classes;
		return Math.round(total);
	}
	const compactNumber = (amount: number) => new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 2 }).format(amount);
	$: parameterEstimate = estimateParameters();

	async function load() { loading = true; try { const result = await api.modelDrafts(); drafts = records(result.drafts); if (drafts.length) await open(String(drafts[0].draft_id)); } catch { drafts = []; } finally { loading = false; } }
	async function open(id: string) { try { const result = await api.modelDraft(id); selected = record(result.draft ?? result); name = String(selected.name ?? 'Untitled V2 classifier'); config = copy(record(selected.config)); report = null; } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not open model draft.'); } }
	async function create() { saving = true; try { const result = await api.createModelDraft({ name, config }); selected = record(result.draft ?? result); await load(); if (selected.draft_id) await open(String(selected.draft_id)); onnotice('Created a versioned model draft.'); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not create model draft.'); } finally { saving = false; } }
	async function save() { if (!selected?.draft_id) return create(); saving = true; try { await api.updateModelDraft(String(selected.draft_id), { name, config }); await open(String(selected.draft_id)); onnotice('Saved model draft revision.'); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not save model draft.'); } finally { saving = false; } }
	async function validate() { if (!selected?.draft_id) { onfailure('Save this draft before validating it.'); return; } try { report = await api.validateModelDraft(String(selected.draft_id)); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not validate model draft.'); } }
	async function cloneArtifact() { if (!sourceArtifactId) return; saving = true; try { const result = await api.createModelDraft({ source_artifact_id: sourceArtifactId, name: `${artifacts.find((item) => String(item.artifact_id) === sourceArtifactId)?.name ?? 'Model'} copy` }); selected = record(result.draft ?? result); await load(); if (selected.draft_id) await open(String(selected.draft_id)); onnotice('Created a draft from the selected sealed model.'); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not clone model configuration.'); } finally { saving = false; } }

	onMount(load);
</script>

<section class="studio-intro">
	<div><p class="eyebrow">MODEL CONSTRUCTION</p><h1>Compose a trainable V2 model.</h1><p>Drafts are editable. Sealed runs are not. Build the input-to-prediction path deliberately, then validate before training.</p></div>
	<div class="studio-actions"><button class="secondary" on:click={() => { selected = null; name = 'Untitled V2 classifier'; config = preset('resnet18'); report = null; }}>New draft</button><button disabled={saving} on:click={save}>{saving ? 'Saving…' : selected ? 'Save revision' : 'Create draft'}</button></div>
</section>

<section class="studio-toolbar panel">
	<label>Draft name<input bind:value={name} placeholder="e.g. Metadata-aware ResNet" /></label>
	<label>Start from<select value={String(value(config, 'encoder.family', 'resnet18'))} on:change={(event) => setFamily(event.currentTarget.value)}><optgroup label="ResNet"><option value="resnet18">ResNet-18</option><option value="resnet34">ResNet-34</option><option value="resnet50">ResNet-50</option><option value="resnet101">ResNet-101</option><option value="resnet152">ResNet-152</option></optgroup><optgroup label="DenseNet"><option value="densenet121">DenseNet-121</option><option value="densenet169">DenseNet-169</option><option value="densenet201">DenseNet-201</option></optgroup><optgroup label="EfficientNetV2"><option value="efficientnet_v2_b0">B0</option><option value="efficientnet_v2_b1">B1</option><option value="efficientnet_v2_b2">B2</option><option value="efficientnet_v2_b3">B3</option><option value="efficientnet_v2_s">Small</option><option value="efficientnet_v2_m">Medium</option><option value="efficientnet_v2_l">Large</option></optgroup><optgroup label="Other"><option value="convnext_tiny">ConvNeXt Tiny</option><option value="convnext_small">ConvNeXt Small</option><option value="mobilenet_v3_small">MobileNetV3 Small</option><option value="mobilenet_v3_large">MobileNetV3 Large</option><option value="simple_cnn">Simple CNN</option><option value="resnet_like">Compact ResNet</option><option value="densenet_like">Compact DenseNet</option></optgroup></select></label>
	<label>Clone a sealed model<select bind:value={sourceArtifactId}><option value="">Choose model…</option>{#each artifacts as artifact}<option value={String(artifact.artifact_id)}>{String(artifact.name ?? artifact.artifact_id)}</option>{/each}</select></label>
	<button class="secondary" disabled={!sourceArtifactId || saving} on:click={cloneArtifact}>Clone</button>
</section>

{#if loading}<section class="panel"><p class="empty">Loading model drafts…</p></section>{:else}
<div class="construction-grid">
	<aside class="draft-rail panel"><div class="panel-head"><div><h2>Draft library</h2><p>Versioned configurations.</p></div><span class="count">{drafts.length}</span></div>{#each drafts as draft}<button class:active={selected?.draft_id === draft.draft_id} on:click={() => open(String(draft.draft_id))}><strong>{String(draft.name)}</strong><small>{String(record(record(draft.config).run).model ?? 'V2 draft')}</small></button>{:else}<p class="empty">Your new draft will appear here after saving.</p>{/each}</aside>
	<div class="construction-main">
		<section class="parameter-estimate panel" aria-live="polite"><div><p class="eyebrow">LIVE DESIGN ESTIMATE</p><h2>{compactNumber(parameterEstimate)} trainable parameters</h2><p>Estimated from the encoder, projection, metadata fields, and classifier. The exact count is resolved when the final model is built against frozen training data.</p></div><label>Output classes<input type="number" min="2" value={Number(value(config, 'data.num_classes', 2))} on:change={(event) => mutate('data.num_classes', Number(event.currentTarget.value))} /></label>{#if selected?.draft_id}<button class="secondary small" on:click={validate}>Validate draft</button>{/if}</section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">01 · INPUT</p><h2>Input & geometry</h2><p>Channels, ROI placement, and preprocessing.</p></div></header><div class="editor-fields"><label>Input height<input type="number" min="16" value={Number(value(config, 'data.input_shape.0', 128))} on:change={(event) => mutate('data.input_shape.0', Number(event.currentTarget.value))} /></label><label>Input width<input type="number" min="16" value={Number(value(config, 'data.input_shape.1', 128))} on:change={(event) => mutate('data.input_shape.1', Number(event.currentTarget.value))} /></label><label>Channels<input value={records(value(config, 'input.channels', [])).join(', ')} on:change={(event) => mutate('input.channels', event.currentTarget.value.split(',').map((item) => item.trim()).filter(Boolean))} /></label><label>ROI geometry<select value={String(value(config, 'input.geometry.type', 'preserve_aspect_pad'))} on:change={(event) => mutate('input.geometry.type', event.currentTarget.value)}><option value="preserve_aspect_pad">Preserve aspect + pad</option><option value="center_roi_pad">Center ROI + pad</option><option value="resize_crop">Resize + crop</option><option value="direct_resize">Direct resize</option></select></label></div></section>
		<AdvancedConfigEditor {config} title="Advanced input controls" description="Preprocessing, channel interpretation, tiling, and remaining input-level options." sections={['data', 'input', 'preprocessing', 'tiling']} excludePaths={['data.input_shape', 'input.channels', 'input.geometry.type']} on:change={(event) => { config = event.detail.config; report = null; }} />
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">02 · CNN ENCODER</p><h2>Backbone & stem</h2><p>Architecture, stem behavior, and normalization.</p></div></header><div class="editor-fields"><label>Architecture<select value={String(value(config, 'encoder.family', 'resnet18'))} on:change={(event) => setFamily(event.currentTarget.value)}><optgroup label="ResNet"><option value="resnet18">ResNet-18</option><option value="resnet34">ResNet-34</option><option value="resnet50">ResNet-50</option><option value="resnet101">ResNet-101</option><option value="resnet152">ResNet-152</option></optgroup><optgroup label="DenseNet"><option value="densenet121">DenseNet-121</option><option value="densenet169">DenseNet-169</option><option value="densenet201">DenseNet-201</option></optgroup><optgroup label="EfficientNetV2"><option value="efficientnet_v2_b0">B0</option><option value="efficientnet_v2_b1">B1</option><option value="efficientnet_v2_b2">B2</option><option value="efficientnet_v2_b3">B3</option><option value="efficientnet_v2_s">Small</option><option value="efficientnet_v2_m">Medium</option><option value="efficientnet_v2_l">Large</option></optgroup><optgroup label="Other"><option value="convnext_tiny">ConvNeXt Tiny</option><option value="convnext_small">ConvNeXt Small</option><option value="mobilenet_v3_small">MobileNetV3 Small</option><option value="mobilenet_v3_large">MobileNetV3 Large</option><option value="simple_cnn">Simple CNN</option><option value="resnet_like">Compact ResNet</option><option value="densenet_like">Compact DenseNet</option></optgroup></select></label><label>Stem kernel<input type="number" min="1" step="2" value={Number(value(config, 'stem.kernel_size', 3))} on:change={(event) => mutate('stem.kernel_size', Number(event.currentTarget.value))} /></label><label>Stem stride<input type="number" min="1" value={Number(value(config, 'stem.stride', 1))} on:change={(event) => mutate('stem.stride', Number(event.currentTarget.value))} /></label><label>Normalization<select value={String(value(config, 'normalization.type', 'batch'))} on:change={(event) => mutate('normalization.type', event.currentTarget.value)}><option value="batch">Batch normalization</option><option value="group">Group normalization</option><option value="layer">Layer normalization</option><option value="none">None</option></select></label></div></section>
		<AdvancedConfigEditor {config} title="Advanced encoder controls" description="Architecture version, family-specific model settings, stem details, and normalization behavior." sections={['architecture', 'encoder', 'stem', 'normalization', 'model']} excludePaths={['encoder.family', 'stem.kernel_size', 'stem.stride', 'normalization.type']} on:change={(event) => { config = event.detail.config; report = null; }} />
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">03 · REPRESENTATION</p><h2>Pooling & embedding</h2><p>Convert encoder features into the image representation.</p></div></header><div class="editor-fields"><label>Pooling<select value={String(value(config, 'pooling.type', 'avg'))} on:change={(event) => mutate('pooling.type', event.currentTarget.value)}><option value="avg">Global average</option><option value="max">Global max</option><option value="avg_max">Average + max</option><option value="gem">Generalized mean</option></select></label><label>Projection<select value={String(value(config, 'image_embedding.projection.type', 'identity'))} on:change={(event) => mutate('image_embedding.projection.type', event.currentTarget.value)}><option value="identity">Identity</option><option value="linear">Linear bottleneck</option><option value="mlp">MLP</option></select></label><label>Output dimension<input type="number" min="1" value={Number(value(config, 'image_embedding.projection.output_dim', 256))} on:change={(event) => mutate('image_embedding.projection.output_dim', Number(event.currentTarget.value))} /></label></div></section>
		<AdvancedConfigEditor {config} title="Advanced representation controls" description="Fine-grained pooling and image-embedding settings." sections={['pooling', 'image_embedding']} excludePaths={['pooling.type', 'image_embedding.projection.type', 'image_embedding.projection.output_dim']} on:change={(event) => { config = event.detail.config; report = null; }} />
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">04 · METADATA & FUSION</p><h2>Optional scalar context</h2><p>Only add fields that are available at inference.</p></div></header><div class="editor-fields"><label>Metadata encoder<select value={String(value(config, 'metadata.encoder.type', 'direct'))} on:change={(event) => mutate('metadata.encoder.type', event.currentTarget.value)}><option value="direct">Direct</option><option value="mlp">MLP</option></select></label><label>Fusion<select value={String(value(config, 'fusion.type', 'concat'))} on:change={(event) => mutate('fusion.type', event.currentTarget.value)}><option value="concat">Concatenate</option><option value="projected">Projected fusion</option></select></label></div><div class="ordered-editor"><div class="panel-head"><div><h3>Metadata fields</h3><p>Drag to set stable feature order.</p></div><button class="secondary small" on:click={addMetadata}>Add field</button></div>{#each fields() as field, index}<article draggable="true" on:dragstart={() => dragIndex = index} on:dragover|preventDefault on:drop={() => reorderMetadata(index)}><span class="drag-handle" aria-label="Drag to reorder">⋮⋮</span><input value={String(field.name ?? '')} aria-label="Metadata field name" on:change={(event) => updateMetadata(index, 'name', event.currentTarget.value)} /><input value={String(field.source ?? '')} aria-label="Metadata field source" on:change={(event) => updateMetadata(index, 'source', event.currentTarget.value)} /><select value={String(field.transform ?? 'identity')} aria-label="Metadata transform" on:change={(event) => updateMetadata(index, 'transform', event.currentTarget.value)}><option value="identity">Identity</option><option value="log1p">log1p</option><option value="sqrt">Square root</option></select><button class="icon-button" aria-label="Remove field" on:click={() => removeMetadata(index)}>×</button></article>{:else}<p class="empty">No metadata inputs. Add one only when it is available at inference.</p>{/each}</div></section>
		<AdvancedConfigEditor {config} title="Advanced metadata and fusion controls" description="Metadata noise, encoder internals, and representation-fusion settings." sections={['metadata', 'fusion']} excludePaths={['metadata.fields', 'metadata.encoder.type', 'fusion.type']} on:change={(event) => { config = event.detail.config; report = null; }} />
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">05 · PRIMARY CLASSIFIER</p><h2>Prediction head</h2><p>Choose how the fused representation becomes a class prediction.</p></div></header><div class="editor-fields"><label>Head type<select value={String(value(config, 'classifier.type', 'linear'))} on:change={(event) => mutate('classifier.type', event.currentTarget.value)}><option value="linear">Linear</option><option value="mlp">MLP</option><option value="cosine">Cosine</option><option value="prototype">Prototype</option></select></label>{#if value(config, 'classifier.type') === 'prototype'}<label>Prototypes per class<input type="number" min="1" value={Number(value(config, 'classifier.prototypes_per_class', 1))} on:change={(event) => mutate('classifier.prototypes_per_class', Number(event.currentTarget.value))} /></label><label>Distance<select value={String(value(config, 'classifier.prototype_metric', 'cosine'))} on:change={(event) => mutate('classifier.prototype_metric', event.currentTarget.value)}><option value="cosine">Cosine</option><option value="euclidean">Euclidean</option></select></label>{/if}</div></section>
		<AdvancedConfigEditor {config} title="Advanced classifier controls" description="Head-specific dimensions, margins, temperatures, and prototype settings." sections={['classifier']} excludePaths={['classifier.type', 'classifier.prototypes_per_class', 'classifier.prototype_metric']} on:change={(event) => { config = event.detail.config; report = null; }} />
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">06 · POST-HOC PREDICTOR</p><h2>Optional downstream estimator</h2><p>Fits only after the neural run, using bounded-memory representation artifacts.</p></div></header><div class="editor-fields"><label class="check-label"><input type="checkbox" checked={Boolean(value(config, 'posthoc.enabled', false))} on:change={(event) => mutate('posthoc.enabled', event.currentTarget.checked)} /> Enable fitted post-hoc predictor</label>{#if Boolean(value(config, 'posthoc.enabled', false))}<label>Embedding source<select value={String(value(config, 'posthoc.representation', 'fused_embedding'))} on:change={(event) => mutate('posthoc.representation', event.currentTarget.value)}><option value="image_embedding">Image embedding</option><option value="fused_embedding">Fused embedding</option></select></label><label>Estimator<select value={String(value(config, 'posthoc.estimator', 'logistic_regression'))} on:change={(event) => mutate('posthoc.estimator', event.currentTarget.value)}><option value="logistic_regression">Logistic regression</option><option value="linear_svm">Linear SVM</option><option value="knn">K-nearest neighbors</option></select></label>{/if}</div><p class="callout">Post-hoc parameters are not included in the neural-model estimate.</p></section>
		<AdvancedConfigEditor {config} title="Advanced post-hoc controls" description="Estimator-specific parameters and bounded-memory artifact behavior." sections={['posthoc']} excludePaths={['posthoc.enabled', 'posthoc.representation', 'posthoc.estimator']} on:change={(event) => { config = event.detail.config; report = null; }} />
		<AdvancedConfigEditor {config} title="Training and execution controls" description="Expert-only training, augmentation, recovery, evaluation, evidence, and output settings." sections={['run', 'training', 'callbacks', 'recovery', 'augmentation', 'distribution', 'self_supervised', 'pretraining', 'evidence', 'inference', 'output', 'evaluation']} on:change={(event) => { config = event.detail.config; report = null; }} />
		{#if report}<section class:invalid={report.valid === false} class="validation-message {report.valid === false ? 'invalid' : 'valid'}"><strong>{report.valid === false ? 'Draft needs attention' : 'Draft validated'}</strong><span>{String(report.message ?? (report.valid === false ? report.error ?? 'Review the reported configuration constraints.' : 'The configuration can be planned for training.'))}</span></section>{/if}
		<section class="construction-footer panel"><div><strong>{selected ? 'Draft is saved as a revision.' : 'Draft is local until you create it.'}</strong><small>Training seals an immutable config snapshot and never mutates this draft.</small></div><button disabled={!selected?.draft_id} on:click={() => selected?.draft_id && ontrain(String(selected.draft_id))}>Use in training</button></section>
	</div>
</div>{/if}
