<script lang="ts">
	import { onMount } from 'svelte';
	import { api, type RecordValue } from '$lib/api';
	import ConfigField from '$lib/config/ConfigField.svelte';
	import StageAdvancedOptions from '$lib/StageAdvancedOptions.svelte';
	import { configWithValue, copyConfig, getPath, setPath } from '$lib/config/paths';
	import type { ConfigFieldDefinition, ConfigurationSchema } from '$lib/config/types';

	export let onnotice: (message: string) => void;
	export let onfailure: (message: string) => void;
	export let ontrain: (definitionId: string) => void;

	const records = (value: unknown): RecordValue[] => Array.isArray(value) ? value as RecordValue[] : [];
	const record = (value: unknown): RecordValue => value && typeof value === 'object' ? value as RecordValue : {};
	const text = (value: unknown) => value == null || value === '' ? '—' : String(value);
	const value = getPath;
	const copy = copyConfig;
	const definitionTask = (definition: RecordValue) => text(
		getPath(record(definition.config), 'run.task', definition.task ?? record(definition.architecture).task)
	);

	let definitions: RecordValue[] = [];
	let templates: RecordValue[] = [];
	let templateId = '';
	let selected: RecordValue | null = null;
	let creating = false;
	let name = 'Untitled V2 classifier';
	let config: RecordValue = {};
	let loading = true;
	let saving = false;
	let report: RecordValue | null = null;
	let dragIndex: number | null = null;
	let schemaFields: RecordValue[] = [];
	let schemaDefaults: RecordValue = {};
	let appliedTemplateId = '';
	$: selectedTemplate = templates.find((item) => String(item.template_id) === templateId);
	$: if (!selected && selectedTemplate && appliedTemplateId !== templateId) { config = copy(record(selectedTemplate.config)); appliedTemplateId = templateId; }
	function fields(): RecordValue[] { const current = value(config, 'metadata.fields', []); return records(current); }
	function mutate(path: string, raw: unknown) { config = configWithValue(config, path, raw); report = null; }
	function field(path: string): ConfigFieldDefinition { return (schemaFields.find((item) => item.path === path) as ConfigFieldDefinition | undefined) ?? { path, label: path.split('.').at(-1)?.replaceAll('_', ' ') }; }
	function addMetadata() { const next = copy(config); const current = fields(); setPath(next, 'metadata.fields', [...current, { name: `field_${current.length + 1}`, source: 'metadata.', transform: 'identity' }]); config = next; }
	function removeMetadata(index: number) { const next = copy(config); setPath(next, 'metadata.fields', fields().filter((_, item) => item !== index)); config = next; }
	function reorderMetadata(index: number) { if (dragIndex === null || dragIndex === index) return; const items = [...fields()]; const [moved] = items.splice(dragIndex, 1); items.splice(index, 0, moved); const next = copy(config); setPath(next, 'metadata.fields', items); config = next; dragIndex = null; }
	function updateMetadata(index: number, key: string, raw: string) { const next = copy(config); const items = fields().map((item, itemIndex) => itemIndex === index ? { ...item, [key]: raw } : item); setPath(next, 'metadata.fields', items); config = next; }
	async function load() { loading = true; try { const [definitionResult, templateResult] = await Promise.all([api.modelDefinitions(), api.modelDefinitionTemplates()]); definitions = records(definitionResult.definitions); templates = records(templateResult.templates); if (!templateId && templates.length) templateId = String(templates[0].template_id); } catch { definitions = []; templates = []; } finally { loading = false; } }
	async function loadSchema() {
		try {
			const schema = await api.configurationSchema() as ConfigurationSchema;
			schemaFields = schema.fields ?? [];
			schemaDefaults = schema.defaults ?? {};
			// Defaults are authored and resolved by the server.  Do not add browser
			// fallback presets: doing so would create a second configuration authority.
			if (!selected && !Object.keys(config).length) config = copy(schemaDefaults);
		} catch { schemaFields = []; }
	}
	function startNew() { selected = null; creating = true; name = 'Untitled V2 classifier'; appliedTemplateId = ''; config = copy(record(templates.find((item) => String(item.template_id) === templateId)?.config)); report = null; }
	async function open(id: string) { try { selected = record(await api.modelDefinition(id)); creating = false; name = String(selected.name ?? 'Untitled V2 definition'); config = copy(record(selected.config)); report = null; } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not open model definition.'); } }
	async function create() { if (!templateId) { onfailure('Choose a maintained V2 template first.'); return; } saving = true; try { selected = record(await api.createModelDefinition({ name, template_id: templateId, config })); await load(); if (selected.definition_id) await open(String(selected.definition_id)); onnotice('Created a versioned V2 model definition from the maintained template.'); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not create model definition.'); } finally { saving = false; } }
	async function save() { if (!selected?.definition_id) return create(); saving = true; try { selected = record(await api.updateModelDefinition(String(selected.definition_id), { name, config, expected_revision: Number(selected.revision) })); await load(); if (selected.definition_id) await open(String(selected.definition_id)); onnotice('Saved a new immutable definition revision.'); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not save model definition.'); } finally { saving = false; } }
	async function duplicate(definition: RecordValue) { if (!definition.definition_id) return; saving = true; try { const result = await api.duplicateModelDefinition(String(definition.definition_id), { revision: Number(definition.revision), lineage_kind: 'sensitivity' }); selected = record(result); creating = false; await load(); if (selected.definition_id) await open(String(selected.definition_id)); onnotice('Created the next version from the pinned definition revision.'); } catch (error) { onfailure(error instanceof Error ? error.message : 'Could not duplicate model definition.'); } finally { saving = false; } }

	onMount(() => { void load(); void loadSchema(); });
</script>

<section class="studio-intro">
	<div><p class="eyebrow">MODEL DEFINITIONS</p><h1>Choose a definition, then construct it.</h1><p>Open a versioned V2 definition from the library or define a new one from a maintained TOML template.</p></div>
</section>

{#if loading}<section class="panel"><p class="empty">Loading model drafts…</p></section>{:else}
<div class="construction-grid">
	<aside class="draft-rail panel"><div class="panel-head"><div><h2>Definition library</h2><p>Versioned V2 configurations.</p></div><span class="count">{definitions.length}</span></div><button class="new-definition" on:click={startNew}>+ Define new model</button>{#each definitions as definition}<article class:active={selected?.definition_id === definition.definition_id}><button class="definition-select" on:click={() => open(String(definition.definition_id))}><strong>{String(definition.name)}</strong><small>revision {String(definition.revision)} · {definitionTask(definition)} · {String(record(definition.architecture).variant ?? 'V2')}</small></button><button class="secondary small duplicate-definition" disabled={saving} on:click={() => duplicate(definition)}>Duplicate</button></article>{:else}<div class="library-empty"><strong>Start your first runnable path</strong><small>1. Create a maintained definition<br />2. Freeze a training set<br />3. Validate it in Queue</small></div>{/each}</aside>
	<div class="construction-main">
		{#if !selected && !creating}<section class="constructor-empty panel"><p class="eyebrow">NEXT STEP · 1 OF 3</p><h2>{definitions.length ? 'Open a definition to continue' : 'Create your first model definition'}</h2><p>{definitions.length ? 'Open a versioned definition from the library to review or create its next revision. When it is ready, Queue pairs that exact revision with frozen data.' : 'Begin from a maintained template. Saving creates a reusable, versioned definition; Queue later pairs it with a frozen training set and validates compute.'}</p><button on:click={startNew}>{definitions.length ? 'Define a new model' : 'Choose a maintained template'}</button></section>{:else}
		<section class="parameter-estimate panel" aria-live="polite"><div><p class="eyebrow">VERSIONED DEFINITION</p><h2>{selected ? `Revision ${String(selected.revision)}` : 'New definition'}</h2><p>Output classes are derived from the frozen training set. Queue validation builds the exact model, materializes the TOML, and checks the selected compute endpoint.</p></div></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">01 · DEFINITION DETAILS</p><h2>Name & maintained template</h2><p>Give this reusable model definition a meaningful experiment name.</p></div></header><div class="editor-fields"><label>Definition name<input bind:value={name} placeholder="e.g. exp001-resnet-128" /></label>{#if selected}<label>Maintained template<input value={text(selected.template_name ?? selected.template_id)} disabled /></label>{:else}<label>Maintained template<select bind:value={templateId}>{#each templates as template}<option value={String(template.template_id)}>{text(template.name ?? template.template_id)} · {text(template.task)} · {text((template.architecture as RecordValue | undefined)?.variant)}</option>{/each}</select></label>{/if}</div><p class="template-capability">Task capability: <strong>{text(value(config, 'run.task', selectedTemplate?.task))}</strong>. The template and task determine the compatible training workflow.</p></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">02 · INPUT</p><h2>Input & geometry</h2><p>Channels, ROI placement, and preprocessing.</p></div></header><div class="editor-fields"><ConfigField definition={field('data.input_shape')} value={value(config, 'data.input_shape')} {config} on:change={(event) => mutate('data.input_shape', event.detail.value)} /><ConfigField definition={field('input.channels')} value={value(config, 'input.channels')} {config} on:change={(event) => mutate('input.channels', event.detail.value)} /><ConfigField definition={field('input.geometry.type')} value={value(config, 'input.geometry.type')} {config} on:change={(event) => mutate('input.geometry.type', event.detail.value)} /></div><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Input refinement, geometry, and tiling." sections={['data', 'input', 'preprocessing', 'tiling']} excludePaths={['data.input_shape', 'input.channels', 'input.geometry.type']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">03 · CNN ENCODER</p><h2>Backbone & stem</h2><p>Architecture, stem behavior, and normalization are defined by the V2 catalog.</p></div></header><div class="editor-fields"><ConfigField definition={field('encoder.family')} value={value(config, 'encoder.family')} {config} on:change={(event) => mutate('encoder.family', event.detail.value)} /><ConfigField definition={field('encoder.variant')} value={value(config, 'encoder.variant')} {config} on:change={(event) => mutate('encoder.variant', event.detail.value)} /><ConfigField definition={field('stem.kernel_size')} value={value(config, 'stem.kernel_size')} {config} on:change={(event) => mutate('stem.kernel_size', event.detail.value)} /><ConfigField definition={field('stem.stride')} value={value(config, 'stem.stride')} {config} on:change={(event) => mutate('stem.stride', event.detail.value)} /><ConfigField definition={field('normalization.type')} value={value(config, 'normalization.type')} {config} on:change={(event) => mutate('normalization.type', event.detail.value)} /></div><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Encoder topology, stem, and normalization." sections={['architecture', 'encoder', 'stem', 'normalization']} excludePaths={['encoder.family', 'encoder.variant', 'stem.kernel_size', 'stem.stride', 'normalization.type']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">04 · REPRESENTATION</p><h2>Pooling & embedding</h2><p>Convert encoder features into the image representation.</p></div></header><div class="editor-fields"><ConfigField definition={field('pooling.type')} value={value(config, 'pooling.type')} {config} on:change={(event) => mutate('pooling.type', event.detail.value)} /><ConfigField definition={field('image_embedding.projection.type')} value={value(config, 'image_embedding.projection.type')} {config} on:change={(event) => mutate('image_embedding.projection.type', event.detail.value)} /><ConfigField definition={field('image_embedding.projection.output_dim')} value={value(config, 'image_embedding.projection.output_dim')} {config} on:change={(event) => mutate('image_embedding.projection.output_dim', event.detail.value)} /></div><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Fine-grained pooling and image-embedding settings." sections={['pooling', 'image_embedding']} excludePaths={['pooling.type', 'image_embedding.projection.type', 'image_embedding.projection.output_dim']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">05 · METADATA & FUSION</p><h2>Optional scalar context</h2><p>Only add fields that are available at inference.</p></div></header><div class="editor-fields"><ConfigField definition={field('metadata.encoder.type')} value={value(config, 'metadata.encoder.type')} {config} on:change={(event) => mutate('metadata.encoder.type', event.detail.value)} /><ConfigField definition={field('fusion.type')} value={value(config, 'fusion.type')} {config} on:change={(event) => mutate('fusion.type', event.detail.value)} /></div><div class="ordered-editor"><div class="panel-head"><div><h3>Metadata fields</h3><p>Drag to set stable feature order.</p></div><button class="secondary small" on:click={addMetadata}>Add field</button></div>{#each fields() as metadataField, index}<article draggable="true" on:dragstart={() => dragIndex = index} on:dragover|preventDefault on:drop={() => reorderMetadata(index)}><span class="drag-handle" aria-label="Drag to reorder">⋮⋮</span><input value={String(metadataField.name ?? '')} aria-label="Metadata field name" on:change={(event) => updateMetadata(index, 'name', event.currentTarget.value)} /><input value={String(metadataField.source ?? '')} aria-label="Metadata field source" on:change={(event) => updateMetadata(index, 'source', event.currentTarget.value)} /><ConfigField definition={field('metadata.fields[].transform')} value={metadataField.transform ?? 'identity'} {config} on:change={(event) => updateMetadata(index, 'transform', String(event.detail.value))} /><button class="icon-button" aria-label="Remove field" on:click={() => removeMetadata(index)}>×</button></article>{:else}<p class="empty">No metadata inputs. Add one only when it is available at inference.</p>{/each}</div><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Metadata regularization, encoder internals, and fusion." sections={['metadata', 'fusion']} excludePaths={['metadata.fields', 'metadata.encoder.type', 'fusion.type']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">06 · PRIMARY CLASSIFIER</p><h2>Prediction head</h2><p>Choose how the fused representation becomes a class prediction.</p></div></header><div class="editor-fields"><ConfigField definition={field('classifier.type')} value={value(config, 'classifier.type')} {config} on:change={(event) => mutate('classifier.type', event.detail.value)} />{#if value(config, 'classifier.type') === 'prototype'}<ConfigField definition={field('classifier.prototypes_per_class')} value={value(config, 'classifier.prototypes_per_class')} {config} on:change={(event) => mutate('classifier.prototypes_per_class', event.detail.value)} /><ConfigField definition={field('classifier.prototype_metric')} value={value(config, 'classifier.prototype_metric')} {config} on:change={(event) => mutate('classifier.prototype_metric', event.detail.value)} />{/if}</div><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Head dimensions and classifier regularization." sections={['classifier']} excludePaths={['classifier.type', 'classifier.prototypes_per_class', 'classifier.prototype_metric']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">07 · POST-HOC PREDICTOR</p><h2>Optional downstream estimator</h2><p>Fits only after the neural run, using bounded-memory representation artifacts.</p></div></header><div class="editor-fields"><ConfigField definition={field('posthoc.enabled')} value={value(config, 'posthoc.enabled')} {config} on:change={(event) => mutate('posthoc.enabled', event.detail.value)} />{#if Boolean(value(config, 'posthoc.enabled', false))}<ConfigField definition={field('posthoc.representation')} value={value(config, 'posthoc.representation')} {config} on:change={(event) => mutate('posthoc.representation', event.detail.value)} /><ConfigField definition={field('posthoc.estimator')} value={value(config, 'posthoc.estimator')} {config} on:change={(event) => mutate('posthoc.estimator', event.detail.value)} />{/if}</div><p class="callout">Only catalog-supported post-hoc estimators are offered here; add new supported choices in the authoritative V2 schema first.</p><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Estimator-specific parameters and artifact behavior." sections={['posthoc']} excludePaths={['posthoc.enabled', 'posthoc.representation', 'posthoc.estimator']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">08 · TRAINING & EXECUTION</p><h2>Training controls</h2><p>The maintained template establishes the task; choose the protocol that will be sealed into the queued run.</p></div></header><div class="editor-fields"><ConfigField definition={field('run.task')} value={value(config, 'run.task')} {config} disabled={true} /><ConfigField definition={field('training.epochs')} value={value(config, 'training.epochs')} {config} on:change={(event) => mutate('training.epochs', event.detail.value)} /><ConfigField definition={field('training.optimizer')} value={value(config, 'training.optimizer')} {config} on:change={(event) => mutate('training.optimizer', event.detail.value)} /><ConfigField definition={field('training.learning_rate')} value={value(config, 'training.learning_rate')} {config} on:change={(event) => mutate('training.learning_rate', event.detail.value)} /><ConfigField definition={field('training.loss')} value={value(config, 'training.loss')} {config} on:change={(event) => mutate('training.loss', event.detail.value)} /><ConfigField definition={field('training.metrics')} value={value(config, 'training.metrics')} {config} on:change={(event) => mutate('training.metrics', event.detail.value)} /><ConfigField definition={field('augmentation.enabled')} value={value(config, 'augmentation.enabled')} {config} on:change={(event) => mutate('augmentation.enabled', event.detail.value)} /><ConfigField definition={field('distribution.strategy')} value={value(config, 'distribution.strategy')} {config} on:change={(event) => mutate('distribution.strategy', event.detail.value)} /></div><StageAdvancedOptions {config} fieldDefinitions={schemaFields} description="Training, evaluation, augmentation, and execution controls." sections={['run', 'training', 'callbacks', 'recovery', 'augmentation', 'distribution', 'self_supervised', 'evidence', 'inference', 'output', 'evaluation']} excludePaths={['run.task', 'training.epochs', 'training.optimizer', 'training.learning_rate', 'training.loss', 'training.metrics', 'augmentation.enabled', 'distribution.strategy']} on:change={(event) => { config = event.detail.config; report = null; }} /></section>
		<section class="panel module-editor builder-section"><header><div><p class="eyebrow">09 · LIVE MONITORING</p><h2>Dashboard watchlist</h2><p>Seal optional evidence thresholds into the definition. They notify in the live dashboard; they never change or stop training.</p></div></header><div class="editor-fields"><ConfigField definition={field('monitoring.primary_metric')} value={value(config, 'monitoring.primary_metric')} {config} on:change={(event) => mutate('monitoring.primary_metric', event.detail.value)} /><ConfigField definition={field('monitoring.target_enabled')} value={value(config, 'monitoring.target_enabled')} {config} on:change={(event) => mutate('monitoring.target_enabled', event.detail.value)} />{#if Boolean(value(config, 'monitoring.target_enabled', false))}<ConfigField definition={field('monitoring.target_metric')} value={value(config, 'monitoring.target_metric')} {config} on:change={(event) => mutate('monitoring.target_metric', event.detail.value)} /><ConfigField definition={field('monitoring.target_value')} value={value(config, 'monitoring.target_value')} {config} on:change={(event) => mutate('monitoring.target_value', event.detail.value)} />{/if}<ConfigField definition={field('monitoring.max_validation_loss_increase_enabled')} value={value(config, 'monitoring.max_validation_loss_increase_enabled')} {config} on:change={(event) => mutate('monitoring.max_validation_loss_increase_enabled', event.detail.value)} />{#if Boolean(value(config, 'monitoring.max_validation_loss_increase_enabled', false))}<ConfigField definition={field('monitoring.max_validation_loss_increase')} value={value(config, 'monitoring.max_validation_loss_increase')} {config} on:change={(event) => mutate('monitoring.max_validation_loss_increase', event.detail.value)} />{/if}<ConfigField definition={field('monitoring.max_generalization_gap_enabled')} value={value(config, 'monitoring.max_generalization_gap_enabled')} {config} on:change={(event) => mutate('monitoring.max_generalization_gap_enabled', event.detail.value)} />{#if Boolean(value(config, 'monitoring.max_generalization_gap_enabled', false))}<ConfigField definition={field('monitoring.max_generalization_gap')} value={value(config, 'monitoring.max_generalization_gap')} {config} on:change={(event) => mutate('monitoring.max_generalization_gap', event.detail.value)} />{/if}</div></section>
		{#if report}<section class:invalid={report.valid === false} class="validation-message {report.valid === false ? 'invalid' : 'valid'}"><strong>{report.valid === false ? 'Draft needs attention' : 'Draft validated'}</strong><span>{String(report.message ?? (report.valid === false ? report.error ?? 'Review the reported configuration constraints.' : 'The configuration can be planned for training.'))}</span></section>{/if}
		<section class="construction-footer panel"><div><strong>{selected ? 'Definition revision is saved.' : 'Definition is local until you create it.'}</strong><small>Open Queue to pair this immutable revision with a frozen training set and validate it before scheduling.</small></div><div class="studio-actions"><button disabled={saving} on:click={save}>{saving ? 'Saving…' : selected ? 'Save revision' : 'Create definition'}</button><button disabled={!selected?.definition_id} on:click={() => selected?.definition_id && ontrain(String(selected.definition_id))}>Open queue workflow</button></div></section>
		{/if}
	</div>
</div>{/if}
